#web settings
# context-path在servlet-path之前   /hh/tt
server.port: 8090
server.context-path: /con
server.servlet-path: /serv

#JPA settings
spring.jpa.show-sql: false
spring.jpa.properties.ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

#DB settings
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/mydb
spring.datasource.name: boot
spring.datasource.username: root
spring.datasource.password: 123456

#thymeleaf
spring.thymeleaf.cache: false

#load
#spring.devtools.restart.enabled: true